error: extern block cannot be declared unsafe issue: https://github.com/rust-lang/rust-bindgen/pull/3015 https://github.com/rust-lang/rust-bindgen/issues/2901
error[E0433]: failed to resolve: could not find `offset_of` in mem
issue:
https://github.com/rust-lang/rust-bindgen/issues/2960

Use unsafe extern instead of extern in blocks for any Rust target after 1.82